# Device configuration service exception codes
DEVICE_CONFIG_TRANSPORT_PROVIDER_EXCEPTION = 900

# Apidispatcher2 error codes
API_DISPATCHER_AUTHENTICATION_FAILED = 800
APPLICATION_REQUIRED_PERMISSIONS_MISSING = 801
COULD_NOT_SEND_REQUEST_TO_DEVICE = 805
INVALID_OR_MISSING_AUTHENTICATION_SESSION = 0
INVALID_OR_MISSING_DEVICE_OR_ACCOUNT_PERMISSIONS = 1

API_DISPATCHER_SCLOUD_MANAGER_CLIENT_CONNECTION_FAILED = 802
API_DISPATCHER_MISSING_DEVICE_METADATA = 803

# Generic error codes
UNKNOWN_EXCEPTION = 1000
DEPRECATED_METHOD_EXCEPTION = 1001
