OWNER="owner"
SURFWIZE_ADMIN="surfwize_admin"
SURFWIZE_REPORTING="surfwize_reporting"
SURFWIZE_FILTERING="surfwize_filtering"
GENERAL_CONFIGURATION= "surfwize_settings"
SURFWIZE_SPHIREWALL_USER="surfwize_sphirewall_user"
SURFWIZE_GUEST_SETTINGS="surfwize_guest_settings"
EDGEWIZE="edgewize"
